root = "."
tmp_dir = "tmp"

[build]
  cmd = "go build -o ./tmp/server ./cmd/server"
  bin = "tmp/server"
  delay = 1000
  include_ext = ["go", "html", "css", "js", "sql", "tmpl"]
  include_dir = ["cmd", "internal", "web", "migrations"]
  exclude_dir = ["tmp", "uploads", ".git", "node_modules"]
  exclude_file = []
  follow_symlink = true

[log]
  time = true

[misc]
  clean_on_exit = true