package ai

import (
	"context"
	"fmt"
	"sort"
	"strings"
)

// MockProvider implements Provider with simple keyword-overlap heuristics.
// It makes no network calls, so the whole application runs and demos
// correctly with zero AI vendor credentials. It also serves as executable
// documentation of the contract every real provider must satisfy.
type MockProvider struct{}

func NewMockProvider() *MockProvider { return &MockProvider{} }

func (m *MockProvider) Name() string { return "mock" }

func (m *MockProvider) RankCandidates(ctx context.Context, job JobContext, candidates []CandidateContext) ([]CandidateRanking, error) {
	rankings := make([]CandidateRanking, 0, len(candidates))
	required := append(append([]string{}, job.MustHave...), job.NiceToHave...)

	for _, c := range candidates {
		overlap := overlapCount(required, c.Skills)
		score := 0.0
		if len(required) > 0 {
			score = (float64(overlap) / float64(len(required))) * 100
		}
		rankings = append(rankings, CandidateRanking{
			CandidateID: c.ID,
			Score:       round1(score),
			Summary:     fmt.Sprintf("%d of %d listed skills matched.", overlap, len(required)),
		})
	}

	sort.Slice(rankings, func(i, j int) bool { return rankings[i].Score > rankings[j].Score })
	return rankings, nil
}

func (m *MockProvider) ExplainMatch(ctx context.Context, job JobContext, candidate CandidateContext) (MatchExplanation, error) {
	var strengths, gaps []string
	for _, req := range job.MustHave {
		if containsFold(candidate.Skills, req) {
			strengths = append(strengths, req)
		} else {
			gaps = append(gaps, req)
		}
	}
	note := "Solid overall alignment with the role."
	if len(gaps) > len(strengths) {
		note = "Meaningful gaps against the role's core requirements."
	}
	return MatchExplanation{Strengths: strengths, Gaps: gaps, OverallNote: note}, nil
}

func (m *MockProvider) SummarizeResume(ctx context.Context, resumeText string) (ResumeSummary, error) {
	words := strings.Fields(resumeText)
	headline := "Candidate summary"
	if len(words) > 6 {
		headline = strings.Join(words[:6], " ") + "..."
	}
	return ResumeSummary{
		Headline:   headline,
		KeySkills:  extractLikelySkills(resumeText),
		Experience: fmt.Sprintf("%d words of resume content analyzed.", len(words)),
		Highlights: []string{"Summary generated by the mock provider — replace with a real model in production."},
	}, nil
}

func (m *MockProvider) RecommendJobs(ctx context.Context, candidate CandidateContext, jobs []JobContext) ([]JobRecommendation, error) {
	recs := make([]JobRecommendation, 0, len(jobs))
	for _, j := range jobs {
		overlap := overlapCount(append(append([]string{}, j.MustHave...), j.NiceToHave...), candidate.Skills)
		total := len(j.MustHave) + len(j.NiceToHave)
		score := 0.0
		if total > 0 {
			score = (float64(overlap) / float64(total)) * 100
		}
		recs = append(recs, JobRecommendation{
			JobID:  j.ID,
			Score:  round1(score),
			Reason: fmt.Sprintf("Matches %d of %d skills listed on %s.", overlap, total, j.Title),
		})
	}
	sort.Slice(recs, func(i, j int) bool { return recs[i].Score > recs[j].Score })
	return recs, nil
}

func (m *MockProvider) SuggestResumeImprovements(ctx context.Context, resumeText string, job *JobContext) ([]string, error) {
	suggestions := []string{
		"Quantify impact with concrete numbers where possible.",
		"Lead each bullet with a strong action verb.",
	}
	if job != nil {
		for _, req := range job.MustHave {
			if !strings.Contains(strings.ToLower(resumeText), strings.ToLower(req)) {
				suggestions = append(suggestions, fmt.Sprintf("Consider addressing experience with %s.", req))
			}
		}
	}
	return suggestions, nil
}

// --- helpers -----------------------------------------------------------------

func overlapCount(required, have []string) int {
	count := 0
	for _, r := range required {
		if containsFold(have, r) {
			count++
		}
	}
	return count
}

func containsFold(list []string, target string) bool {
	for _, v := range list {
		if strings.EqualFold(strings.TrimSpace(v), strings.TrimSpace(target)) {
			return true
		}
	}
	return false
}

func round1(v float64) float64 {
	return float64(int(v*10)) / 10
}

func extractLikelySkills(text string) []string {
	// Placeholder heuristic; a real provider would use an actual model here.
	candidates := []string{"Go", "PostgreSQL", "JavaScript", "Python", "React", "SQL", "Docker", "Kubernetes", "AWS", "Leadership"}
	var found []string
	lower := strings.ToLower(text)
	for _, c := range candidates {
		if strings.Contains(lower, strings.ToLower(c)) {
			found = append(found, c)
		}
	}
	return found
}
